export const LOAD_TABLE_DATA = 'LOAD_TABLE_DATA';
export const SORT_TABLE = 'SORT_TABLE';
export const SET_PAGE = 'SET_PAGE';
export const CHANGE_ITEMS_PER_PAGE = 'CHANGE_ITEMS_PER_PAGE';
export const UPDATE_TABLE_DATA = 'UPDATE_TABLE_DATA';
export const SET_SEARCH = 'SET_SEARCH';
